version: '3'
services:
  help-with-prison-visits-async-worker:
    build:
      context: .
    volumes:
      - "./app:/usr/src/app/app"
      - "./logs:/usr/src/app/logs"
      - "./payments:/usr/src/app/payments"
    ports:
      - "3999:3999"
    env_file: ./.env
