apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-cron-payment-run
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  schedule: "5 0 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: payment-run
            image: quay.io/hmpps/help-with-prison-visits-asynchronous-worker
            args:
            - node
            - start-schedule-payment-run
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
