apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-cron-worker-tasks
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker-tasks
              image: quay.io/hmpps/help-with-prison-visits-asynchronous-worker
              command: ["npm"]
              args: ["run", "start-worker-tasks"]
          restartPolicy: Never
