apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . }}-worker-tasks
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker-tasks
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            args:
            - node
            - start-worker-tasks
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
