---
# Values here are the same across all environments
generic-service:
  nameOverride: help-with-prison-visits-asynchronous-worker

  image:
    repository: quay.io/hmpps/help-with-prison-visits-asynchronous-worker
    tag: app_version    # override at deployment time
    port: 3999
  
  service:
    type: ClusterIP
    port: 3999
    targetPort: 3999

  livenessProbe:
    httpGet:
      path: /status
      port: http
  
  readinessProbe:
    httpGet:
      path: /status
      port: http
  
  env:
    PAYOUT_SFTP_HOST: "51.140.191.219"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    help-with-prison-visits-asynchronous-worker:
      APVS_DATABASE: "APVS_DATABASE"
      APVS_ASYNC_WORKER_USERNAME: "APVS_ASYNC_WORKER_USERNAME"
      APVS_ASYNC_WORKER_PASSWORD: "APVS_ASYNC_WORKER_PASSWORD"
      APPINSIGHTS_INSTRUMENTATIONKEY: "APVS_APP_INSIGHTS_INSTRUMENTATION_KEY"
      APVS_NOTIFY_API_KEY: "APVS_NOTIFY_API_KEY"
      APVS_NOTIFY_CLIENT_ID: "APVS_NOTIFY_CLIENT_ID"
      PAYOUT_SFTP_USER: "PAYOUT_SFTP_USER"
      PAYOUT_SFTP_PASSWORD: "PAYOUT_SFTP_PASSWORD"
      APVS_DISTANCE_CALCULATION_DIRECTIONS_API_KEY: "APVS_DISTANCE_CALCULATION_DIRECTIONS_API_KEY"
    rds-sqlserver-instance-output:
      APVS_DATABASE_SERVER: 'rds_instance_address'
