---
# Environment specific values, override helm_deploy/help-with-prison-visits-external/values.yaml
generic-service:
  replicaCount: 2

  env:
    APVS_DWP_BENEFIT_CHECKER_ENABLED: "false"
    # APVS_MOJ_SSO_REDIRECT_URI: 'https://manage.hwpv-dev.hmpps.service.justice.gov.uk/auth/hmppsauth/callback'
    # APVS_MOJ_SSO_TOKEN_HOST: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits-dev.service.justice.gov.uk'
