---
# Environment specific values, override helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml
generic-service:
  replicaCount: 2

  env:
    APVS_DWP_BENEFIT_CHECKER_ENABLED: "true"
    APVS_DWP_BENEFIT_CHECKER_URL: "https://benefitchecker.legalservices.gov.uk/lsx/lsc-services/benefitChecker"
    APVS_ZENDESK_ENABLED: "true"
    APVS_ZENDESK_API_URL: "https://ministryofjustice.zendesk.com"
    APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits.service.justice.gov.uk'

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits
